config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    get 'index',                    to: 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    resources :products, only: [:show] do
      collection do
        get 'search'
      end
    end
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :add_price_image, -> { includes(master: [:default_price, :images]) }
  scope :new_products,    -> { order(available_on: :desc) }
  scope :old_products,    -> { order(available_on: :asc) }
  scope :position_order,  -> { order("spree_assets.position" => :asc) }
  scope :sort_by_order,   -> (sort) do
    case sort
    when "NEW_PRODUCTS"
      reorder(nil).new_products
    when "OLD_PRODUCTS"
      reorder(nil).old_products
    when "LOW_PRICE"
      unscope(:order).ascend_by_master_price
    when "HIGH_PRICE"
      unscope(:order).descend_by_master_price
    else
      reorder(nil).new_products
    end
  end
  scope :search_option,   -> (option_value) do
    joins(variants: :option_values).
    where(spree_option_values: { name: option_value })
  end
  scope :search_word,     -> (search_word) do
    search_word = sanitize_sql_like(search_word)
    where('name LIKE ? OR description LIKE ?', "%#{ search_word }%", "%#{ search_word }%") if search_word.present?
  end

  def related_products
    Spree::Product.in_taxons(taxons).
      add_price_image.
      where.not(id: id).
      distinct
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_products_option

  def show
    @taxon         = Spree::Taxon.find(params[:id])
    @taxonomies    = Spree::Taxonomy.includes(:taxons)
    @colors        = Spree::OptionType.find_by(presentation: "Color").option_values
    @sizes         = Spree::OptionType.find_by(presentation: "Size").option_values
    @products      = products_search.sort_by_order(params[:sort]).position_order
  end

  private

  def base_products
    Spree::Product.in_taxon(@taxon)
  end

  def count_products_option(option_value)
    base_products.search_option(option_value).count
  end

  def products_search
    master_products = base_products.add_price_image
    params[:option].blank? ? master_products : master_products.search_option(params[:option])
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_ITEM_COUNT = 12
  POPULAR_TAXONS     = %w(Clothing Bags Mugs).freeze

  def index
    @popular_taxons = Spree::Taxon.where(name: POPULAR_TAXONS)
    @new_products   = Spree::Product.add_price_image.new_products.limit(MAX_NEW_ITEM_COUNT)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_RELATED_ITEM_COUNT = 12
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.limit(MAX_RELATED_ITEM_COUNT)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.add_price_image.search_word(@search_word)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head_settings.html.erb
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

<!-- CUSTOM CSS -->

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <%= render 'layouts/search_box' %>
            <li class="dropdown">
              <%= link_to "#", data: { toggle: "dropdown disabled" } do %>
                <i class="fa fa-shopping-cart"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_path, class: "navbar-brand" do %>
          <%= image_tag "img/logo.png", :alt => "BIGBAG" %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_search_box.html.erb
<li class="dropdown searchBox">
  <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
  <ul class="dropdown-menu dropdown-menu-right">
    <li>
      <%= form_with url: search_potepan_products_path, id: "form01", class:"input-group", method: :get, local: true, skip_enforcing_utf8: true do |f| %>
        <%= f.text_field :search, class: "form-control", placeholder: "Search…", 'aria-describedby': "basic-addon2" %>
        <%= tag.button tag.span "検索", class: 'input-group-addon addPointer', id: "basic-addon2", onclick: "submit(this.form)" %>
      <% end %>
    </li>
  </ul>
</li>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head_settings' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#category_<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
            <ul id="category_<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.taxons.each do |taxon| %>
                <% next unless taxon.leaf? %>
                <li>
                  <%= link_to potepan_category_path(taxon.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %>
                    <span>(<%= taxon.all_products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_colors.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <%= render partial: 'option', collection: colors, as: :option_value %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_area.html.erb
<div class="col-xs-6">
  <%= render 'filter_sort' %>
</div>
<div class="col-xs-6">
  <%= render 'filter_layout' %>
</div>

app/views/potepan/categories/_filter_layout.html.erb
<div class="btn-group pull-right" role="group">
  <%= link_to potepan_category_path(params[:id], layout: "Grid", option: params[:option], sort: params[:sort]), class: "btn btn-default #{ "active" if !params.key?(:layout) || params[:layout] == "Grid" }" do %>
    <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
  <% end %>
  <%= link_to potepan_category_path(params[:id], layout: "List", option: params[:option], sort: params[:sort]), class: "btn btn-default #{ "active" if params[:layout] == "List" }" do %>
    <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
  <% end %>
</div>

app/views/potepan/categories/_filter_sort.html.erb
<%= form_tag request.path, method: :get, enforce_utf8: false do %>
  <%= hidden_field_tag :option, params[:option] if params[:option] %>
  <%= hidden_field_tag :layout, params[:layout] if params[:layout] %>
  <%= select_tag "sort", options_for_select([
    ["新着順", "NEW_PRODUCTS"],
    ["安い順", "LOW_PRICE"],
    ["高い順", "HIGH_PRICE"],
    ["古い順", "OLD_PRODUCTS"]],
    selected: params[:sort] || "NEW_PRODUCTS"),
    { id: "guiest_id1", class: "select-drop", onchange: "submit(this.form)"} %>
<% end %>

app/views/potepan/categories/_option.html.erb
<li>
  <%= link_to potepan_category_path(option: option_value.name, sort: params[:sort], layout: params[:layout]) do %>
    <%= option_value.name %><span>(<%= count_products_option(option_value.name) %>)</span>
  <% end %>
</li>

app/views/potepan/categories/_product.html.erb
<% if params[:layout] == "List" %>
  <div class="col-xs-12">
    <%= link_to potepan_product_path(product.id) do %>
      <div class="media">
        <div class="media-left">
          <%= image_tag product.display_image.attachment(:product), alt: product.name, class: "media-object" %>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%= product.name %>
          </h4>
          <p><%= product.description %></p>
          <h3><%= product.display_price %></h3>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="productBox col-sm-4 col-xs-12">
    <%= render 'shared/products_card', object_product: product %>
  </div>
<% end %>

app/views/potepan/categories/_sizes.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <%= render partial: 'option', collection: sizes, as: :option_value %>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<!-- LIGHT SECTION -->
<%= render 'shared/product_bar', title_name: @taxon.name, active_name: @taxon.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'categories', taxonomies: @taxonomies %>
        <%= render 'colors', colors: @colors %>
        <%= render 'sizes', sizes: @sizes %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <%= render 'filter_area' %>
        </div>
        <div class="row productListSingle">
          <%= render partial: 'product', collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<%= render 'shared/brand_bar' %>

app/views/potepan/home/_banner.html.erb
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag "home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data: { bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat" } %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/home/_new_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <%= render 'shared/products_slider', object_products: object_products %>
</div>

app/views/potepan/home/_popular_categories.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <% popular_taxons.each do |popular_taxon| %>
    <div class="col-sm-4 col-xs-12">
      <div class="thumbnail">
        <%= link_to potepan_category_path(popular_taxon.id) do %>
          <div class="imageWrapper">
            <%= image_tag "home/featured-collection/featured-collection-#{popular_taxon.name}.jpg",
              alt: "feature-collection-#{popular_taxon.name}-image" %>
            <div class="masking">
              <div class="btn viewBtn">View <%= popular_taxon.name %></div>
            </div>
          </div>
          <div class="caption">
            <h4><%= popular_taxon.name %></h4>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/home/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <!-- <option value="0">数</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/home/index.html.erb
<!-- BANNER -->
<%= render 'banner' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <%= render 'popular_categories', popular_taxons: @popular_taxons %>
    <%= render 'new_products', object_products: @new_products %>
  </div>
</section>
<!-- LIGHT SECTION -->
<%= render 'shared/brand_bar' %>
<!-- PRODUCT QUICK VIEW MODAL -->
<%= render 'product_quick_view_modal' %>

app/views/potepan/products/_media_body.html.erb
<div class="media-body">
  <ul class="list-inline">
    <%= link_to potepan_category_path(product.taxons.first.id) do %>
      <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
    <% end %>
  </ul>
  <h2><%= product.name %></h2>
  <h3><%= product.display_price %></h3>
  <p><%= product.description %></p>
  <span class="quick-drop">
    <select name="guiest_id3" id="guiest_id3" class="select-drop">
      <option value="0">S</option>
      <option value="1">M</option>
      <option value="2">L</option>
      <option value="3">XL</option>
    </select>
  </span>
  <span class="quick-drop resizeWidth">
    <select name="guiest_id4" id="guiest_id4" class="select-drop">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select>
  </span>
  <div class="btn-area">
    <%= link_to "#", class: "btn btn-primary btn-block" do %>
      <i class="fa fa-angle-right" aria-hidden="true"></i>カートへ入れる
    <% end %>
  </div>
</div>

app/views/potepan/products/_media_image.html.erb
<div class="media-left productSlider">
  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% product.images.each_with_index do |image, index| %>
        <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
          <%= image_tag image.attachment.url(:large), alt: "product-img" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="clearfix">
    <div id="thumbcarousel" class="carousel slide" data-interval="false">
      <div class="carousel-inner">
        <% product.images.each_with_index do |image, index| %>
          <div class="thumb" data-target="#carousel" data-slide-to="<%= index %>">
            <%= image_tag image.attachment.url(:product), alt: "product-img" %>
          </div>
        <% end %>
      </div>
      <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
  </div>
</div>

app/views/potepan/products/_products_content.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <%= render 'shared/products_slider', object_products: object_products %>
</div>

app/views/potepan/products/_single_product.html.erb
<div class="row singleProduct">
  <div class="col-xs-12">
    <div class="media">
      <%= render 'media_image', product: product %>
      <%= render 'media_body',  product: product %>
    </div>
  </div>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "Results by Search #{ @search_word }" ) %>
<!-- LIGHT SECTION -->
<%= render 'shared/product_bar', title_name: "'#{@search_word}' 検索結果： #{@products.count} 件", active_name: "search" %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
        <div class="productBox col-sm-3 col-xs-12">
          <%= render 'shared/products_card', object_product: product %>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<%= render 'shared/brand_bar' %>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name ) %>
<!-- LIGHT SECTION -->
<%= render 'shared/product_bar', title_name: @product.name, active_name: @product.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <%= render 'single_product', product: @product %>
    <%= render 'products_content', object_products: @related_products %>
  </div>
</section>

app/views/shared/_brand_bar.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_product_bar.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= title_name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><%= link_to "Home", potepan_path %></li>
          <li><%= link_to "shop", "#" %></li>
          <li class="active"><%= active_name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/shared/_products_card.html.erb
<%= link_to potepan_product_path(object_product.id) do %>
  <div class="productImage clearfix">
    <%= image_tag object_product.display_image.attachment(:large), alt: "#{object_product.name}-img" %>
  </div>
  <div class="productCaption clearfix">
    <h5><%= object_product.name %></h5>
    <h3><%= object_product.display_price %></h3>
  </div>
<% end %>

app/views/shared/_products_slider.html.erb
<div class="col-xs-12">
  <div class="productBox owl-carousel featuredProductsSlider">
    <% object_products.each do |object_product| %>
      <div class="slide">
        <%= render 'shared/products_card', object_product: object_product %>
      </div>
    <% end %>
  </div>
</div>